server:
  port: 8073
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8071/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: eureka-consumer
